---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-demo2
  labels:
    app.kubernetes.io/name: helios-demo2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helios-demo2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helios-demo2
    spec:
      containers:
        - name: helios-demo2
          image: docker.io/vfarcic/helios-demo2:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
