---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: helios-demo
  labels:
    app.kubernetes.io/name: helios-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helios-demo
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
